url: //hhm-bjfu.github.io

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  
# Automatically excerpt description in homepage as preamble text.
excerpt_description: true

webrick:
  headers:
    Access-Control-Allow-Origin: "*"

plugins:
  - jekyll-feed
  
